"""Regenerates scripts/liquidity_tranches.txt from db_cache.sweep_tranches --
the DB is the source of truth (see db_cache._ensure_sweep_tranches_table's
comment for why), this just renders it into the exact plain-text format
run_liquidity_tranches.sh/liquidity_tranche_progress.py already parse, so
neither of those needs to change. Run this after any add_tranche_ticker/
remove_tranche_ticker call, before the next sweep run.

Usage: .venv/bin/python scripts/render_liquidity_tranches.py
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import db_cache

CAMPAIGN = 'liquidity_screen'
OUT_PATH = Path(__file__).resolve().parent / 'liquidity_tranches.txt'


def main():
    cfg = db_cache.get_sweep_campaign_config(CAMPAIGN)
    if cfg is None:
        print(f"No sweep_campaign_config row for campaign={CAMPAIGN!r} -- "
              f"run scripts/migrate_liquidity_tranches_to_db.py first.")
        sys.exit(1)
    tranches = db_cache.get_tranches(CAMPAIGN)

    lines = [
        "# Auto-generated by scripts/render_liquidity_tranches.py from "
        "db_cache.sweep_tranches -- DO NOT hand-edit this file.",
        "# To change tranche membership: db_cache.add_tranche_ticker/"
        "remove_tranche_ticker(campaign, tranche_num, ticker, reason=...),",
        "# then rerun scripts/render_liquidity_tranches.py. "
        "scripts/liquidity_tranche_audit.py shows the real history "
        "(including removed tickers and why).",
        "#",
        f"VERSION={cfg['version']}",
        f"FIXED_SLS={cfg['fixed_sls']}",
        f"STRATEGIES={cfg['strategies']}",
        f"ENTRY_TIMING={cfg['entry_timing']}",
        "#",
        "# Tranches: \"<number> <space-separated tickers>\"",
    ]
    for n in sorted(tranches):
        lines.append(f"{n} {' '.join(tranches[n])}")

    OUT_PATH.write_text("\n".join(lines) + "\n")
    print(f"Wrote {OUT_PATH} -- {sum(len(v) for v in tranches.values())} active "
          f"tickers across {len(tranches)} tranches.")


if __name__ == '__main__':
    main()
